import { FileText, BarChart2, FileQuestion, Settings, Database, GitBranch, Layers } from "lucide-react"

export const moduleData = [
  {
    id: "forms",
    name: "Forms",
    description: "Create and manage digital forms and surveys",
    icon: FileText,
    href: "/forms",
    category: "Core Modules",
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "Data visualization and reporting tools",
    icon: BarChart2,
    href: "/analytics",
    category: "Core Modules",
  },
  {
    id: "pir",
    name: "Public Information Requests",
    description: "Manage and process public information requests",
    icon: FileQuestion,
    href: "/pir",
    category: "Core Modules",
  },
  {
    id: "settings",
    name: "System Settings",
    description: "Configure system-wide settings, users, roles, and permissions",
    icon: Settings,
    href: "/settings",
    category: "Admin",
    adminOnly: true,
  },
  {
    id: "integrations",
    name: "Integrations",
    description: "Connect with external services and APIs",
    icon: Database,
    href: "/integrations",
    category: "Admin",
    adminOnly: true,
  },
  {
    id: "workflows",
    name: "Workflows",
    description: "Automate business processes and approvals",
    icon: GitBranch,
    href: "/workflows",
    category: "Coming Soon",
    comingSoon: true,
  },
  {
    id: "projects",
    name: "Projects",
    description: "Project management and collaboration",
    icon: Layers,
    href: "/projects",
    category: "Coming Soon",
    comingSoon: true,
  },
]
